namespace CustomCraft2SML
{
#if SUBNAUTICA
    public enum FoodModel
    {
        None = TechType.None,
        BigFilteredWater = TechType.BigFilteredWater,
        DisinfectedWater = TechType.DisinfectedWater,
        FilteredWater = TechType.FilteredWater,
        StillsuitWater = TechType.StillsuitWater,
        BulboTreePiece = TechType.BulboTreePiece,
        PurpleVegetable = TechType.PurpleVegetable,
        CreepvinePiece = TechType.CreepvinePiece,
        JellyPlant = TechType.JellyPlant,
        KooshChunk = TechType.KooshChunk,
        HangingFruit = TechType.HangingFruit,
        Melon = TechType.Melon,
        NutrientBlock = TechType.NutrientBlock,
        CookedPeeper = TechType.CookedPeeper,
        CookedHoleFish = TechType.CookedHoleFish,
        CookedGarryFish = TechType.CookedGarryFish,
        CookedReginald = TechType.CookedReginald,
        CookedBladderfish = TechType.CookedBladderfish,
        CookedHoverfish = TechType.CookedHoverfish,
        CookedSpadefish = TechType.CookedSpadefish,
        CookedBoomerang = TechType.CookedBoomerang,
        CookedEyeye = TechType.CookedEyeye,
        CookedOculus = TechType.CookedOculus,
        CookedHoopfish = TechType.CookedHoopfish,
        CookedSpinefish = TechType.CookedSpinefish,
        CookedLavaEyeye = TechType.CookedLavaEyeye,
        CookedLavaBoomerang = TechType.CookedLavaBoomerang,
        CuredPeeper = TechType.CuredPeeper,
        CuredHoleFish = TechType.CuredHoleFish,
        CuredGarryFish = TechType.CuredGarryFish,
        CuredReginald = TechType.CuredReginald,
        CuredBladderfish = TechType.CuredBladderfish,
        CuredHoverfish = TechType.CuredHoverfish,
        CuredSpadefish = TechType.CuredSpadefish,
        CuredBoomerang = TechType.CuredBoomerang,
        CuredEyeye = TechType.CuredEyeye,
        CuredOculus = TechType.CuredOculus,
        CuredHoopfish = TechType.CuredHoopfish,
        CuredSpinefish = TechType.CuredSpinefish,
        CuredLavaEyeye = TechType.CuredLavaEyeye,
        CuredLavaBoomerang = TechType.CuredLavaBoomerang,
    }
#elif BELOWZERO
    public enum FoodModel
    {
        None = TechType.None,
        BigFilteredWater = TechType.BigFilteredWater,
        DisinfectedWater = TechType.DisinfectedWater,
        FilteredWater = TechType.FilteredWater,
        StillsuitWater = TechType.StillsuitWater,
        SpicyFruitSalad = TechType.SpicyFruitSalad,
        PurpleVegetable = TechType.PurpleVegetable,
        CreepvinePiece = TechType.CreepvinePiece,
        JellyPlant = TechType.JellyPlant,
        WaterPurificationTablet = TechType.WaterPurificationTablet,
        HangingFruit = TechType.HangingFruit,
        Melon = TechType.Melon,
        NutrientBlock = TechType.NutrientBlock,
        Coffee = TechType.Coffee,
        CookedBladderfish = TechType.CookedBladderfish,
        CookedBoomerang = TechType.CookedBoomerang,
        CookedHoopfish = TechType.CookedHoopfish,
        CookedSpinefish = TechType.CookedSpinefish,
        CookedSpinnerfish = TechType.CookedSpinnerfish,
        CookedArcticPeeper = TechType.CookedArcticPeeper,
        CookedArrowRay = TechType.CookedArrowRay,
        CookedSymbiote = TechType.CookedSymbiote,
        CookedNootFish = TechType.CookedNootFish,
        CookedTriops = TechType.CookedTriops,
        CookedFeatherFish = TechType.CookedFeatherFish,
        CookedFeatherFishRed = TechType.CookedFeatherFishRed,
        CookedDiscusFish = TechType.CookedDiscusFish,
        CuredBladderfish = TechType.CuredBladderfish,
        CuredBoomerang = TechType.CuredBoomerang,
        CuredHoopfish = TechType.CuredHoopfish,
        CuredSpinefish = TechType.CuredSpinefish,
        CuredSpinnerfish = TechType.CuredSpinnerfish,
        CuredArcticPeeper = TechType.CuredArcticPeeper,
        CuredArrowRay = TechType.CuredArrowRay,
        CuredSymbiote = TechType.CuredSymbiote,
        CuredNootFish = TechType.CuredNootFish,
        CuredTriops = TechType.CuredTriops,
        CuredFeatherFish = TechType.CuredFeatherFish,
        CuredFeatherFishRed = TechType.CuredFeatherFishRed,
        CuredDiscusFish = TechType.CuredDiscusFish,
    }
#endif
}