namespace CustomCraft2SML
{
    public enum FoodModel
    {
        None = TechType.None,
        BigFilteredWater = TechType.BigFilteredWater,
        DisinfectedWater = TechType.DisinfectedWater,
        FilteredWater = TechType.FilteredWater,
        StillsuitWater = TechType.StillsuitWater,
        BulboTreePiece = TechType.BulboTreePiece,
        PurpleVegetable = TechType.PurpleVegetable,
        CreepvinePiece = TechType.CreepvinePiece,
        JellyPlant = TechType.JellyPlant,
        KooshChunk = TechType.KooshChunk,
        HangingFruit = TechType.HangingFruit,
        Melon = TechType.Melon,
        NutrientBlock = TechType.NutrientBlock,
        CookedPeeper = TechType.CookedPeeper,
        CookedHoleFish = TechType.CookedHoleFish,
        CookedGarryFish = TechType.CookedGarryFish,
        CookedReginald = TechType.CookedReginald,
        CookedBladderfish = TechType.CookedBladderfish,
        CookedHoverfish = TechType.CookedHoverfish,
        CookedSpadefish = TechType.CookedSpadefish,
        CookedBoomerang = TechType.CookedBoomerang,
        CookedEyeye = TechType.CookedEyeye,
        CookedOculus = TechType.CookedOculus,
        CookedHoopfish = TechType.CookedHoopfish,
        CookedSpinefish = TechType.CookedSpinefish,
        CookedLavaEyeye = TechType.CookedLavaEyeye,
        CookedLavaBoomerang = TechType.CookedLavaBoomerang,
        CuredPeeper = TechType.CuredPeeper,
        CuredHoleFish = TechType.CuredHoleFish,
        CuredGarryFish = TechType.CuredGarryFish,
        CuredReginald = TechType.CuredReginald,
        CuredBladderfish = TechType.CuredBladderfish,
        CuredHoverfish = TechType.CuredHoverfish,
        CuredSpadefish = TechType.CuredSpadefish,
        CuredBoomerang = TechType.CuredBoomerang,
        CuredEyeye = TechType.CuredEyeye,
        CuredOculus = TechType.CuredOculus,
        CuredHoopfish = TechType.CuredHoopfish,
        CuredSpinefish = TechType.CuredSpinefish,
        CuredLavaEyeye = TechType.CuredLavaEyeye,
        CuredLavaBoomerang = TechType.CuredLavaBoomerang,
    }
}